{
 "title": "Validator Client",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Lighthouse Metrics\n\nMetrics collected from a Lighthouse Beacon Node.\n\n\n\n"
   }
  },
  {
   "title": "Validator Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "eth2_validator_balance" }
   ]
  },
  {
   "title": "APR proj.",
   "type": "stat",
   "description": "Based on data from the last 3 days",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(deriv(eth2_validator_balance[3d])*604800*52)/(avg(vc_validators_enabled_count)*32)*100"
    }
   ]
  },
  {
   "title": "Daily (measured)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(eth2_validator_balance[1d]))"
    }
   ]
  },
  {
   "title": "Weekly (measured)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(eth2_validator_balance[1w]))"
    }
   ]
  },
  {
   "title": "Yearly (measured)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(eth2_validator_balance[1y]))"
    }
   ]
  },
  {
   "title": "Successful Attestations per hour",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(vc_signed_attestations_total[1h])"
    }
   ]
  },
  {
   "title": "Validator Balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth2_validator_balance" }
   ]
  },
  {
   "title": "Daily (proj.)",
   "type": "stat",
   "description": "Based on data from the last 3 hours",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(deriv(eth2_validator_balance[3h])*86400)"
    }
   ]
  },
  {
   "title": "Weekly (proj.)",
   "type": "stat",
   "description": "Based on data from the last day",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(deriv(eth2_validator_balance[1d])*604800)"
    }
   ]
  },
  {
   "title": "Yearly (proj.)",
   "type": "stat",
   "description": "Based on data from the last 3 days",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "deriv(eth2_validator_balance[3d])*604800*52"
    }
   ]
  },
  {
   "title": "Daily (proj.)",
   "type": "graph",
   "description": "Based on data from the last day",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(eth2_validator_balance[1d])*86400)"
    }
   ]
  },
  {
   "title": "Weekly (proj.)",
   "type": "graph",
   "description": "Based on data from the last day",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(eth2_validator_balance[1d])*604800)"
    }
   ]
  },
  {
   "title": "Yearly (proj.)",
   "type": "graph",
   "description": "Based on data from the last day",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(eth2_validator_balance[1d])*604800*52)"
    }
   ]
  },
  {
   "title": "Local Beacon Block Proposers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "BeaconBlock" }
   ],
   "targets": [
    { "expr": "vc_beacon_block_proposer_count" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "\n### Consensus\n\nOverview of consensus between nodes.\n\n\n"
   }
  },
  {
   "title": "Average Load (loadavg 1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "system_loadavg_1" }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "system_virt_mem_free_bytes" }
   ]
  },
  {
   "title": "Validator Client Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "\n### Consensus\n\nOverview of consensus between nodes.\n\n\n"
   }
  },
  {
   "title": "Distance from Genesis Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "dtdurations", "label": "Seconds" }
   ],
   "targets": [
    { "expr": "vc_genesis_distance_seconds" }
   ]
  },
  {
   "title": "Enabled Validators",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Validators" }
   ],
   "targets": [
    { "expr": "vc_validators_enabled_count" }
   ]
  },
  {
   "title": "Total Validators",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Validators" }
   ],
   "targets": [
    { "expr": "vc_validators_total_count" }
   ]
  },
  {
   "title": "Local Attesters",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    { "expr": "vc_beacon_attester_count" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "\n### Consensus\n\nOverview of consensus between nodes.\n\n\n"
   }
  },
  {
   "title": "Block Signing Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "BeaconBlock" }
   ],
   "targets": [
    { "expr": "vc_signed_beacon_blocks_total" }
   ]
  },
  {
   "title": "Attestation Signing Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    { "expr": "vc_signed_attestations_total" }
   ]
  },
  {
   "title": "Aggregate Signing Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "SignedAggregateAndProof" }
   ],
   "targets": [
    { "expr": "vc_signed_aggregates_total" }
   ]
  },
  {
   "title": "Selection Proof Signing Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "SelectionProof" }
   ],
   "targets": [
    {
     "expr": "vc_signed_selection_proofs_total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 43 },
   "options": {
    "content": "\n### Consensus\n\nOverview of consensus between nodes.\n\n\n"
   }
  },
  {
   "title": "Duties Service Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vc_duties_service_task_times_seconds_sum[30s])\n/\nrate(vc_duties_service_task_times_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Fork Service Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vc_fork_service_task_times_seconds_sum[30s])\n/\nrate(vc_fork_service_task_times_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Attestation Service Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vc_attestation_service_task_times_seconds_sum[30s])\n/\nrate(vc_attestation_service_task_times_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Block Service Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vc_beacon_block_service_task_times_seconds_sum[30s])\n/\nrate(vc_beacon_block_service_task_times_seconds_count[30s])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "\n### Logs\n\nOverview of logs (includes beacon nodes)\n\n\n"
   }
  },
  {
   "title": "Info Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(info_total[1m])" }
   ]
  },
  {
   "title": "Warn Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(warn_total[1m])" }
   ]
  },
  {
   "title": "Error Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(error_total[1m])" }
   ]
  },
  {
   "title": "Crit Logs Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "crit_total" }
   ]
  }
 ]
}